apiVersion: v1
kind: Service
metadata:
  name: {{ include "tc.fullname" . }}-connector
  namespace: {{ .Values.global.namespace }}
spec:
  selector: { app: {{ include "tc.fullname" . }}-connector }
  ports:
    - name: api
      port: {{ .Values.connector.service.apiPort }}
      targetPort: {{ .Values.connector.service.apiPort }}
    - name: ftp
      port: {{ .Values.connector.service.ftpPort }}
      targetPort: {{ .Values.connector.service.ftpPort }}
