name: Feature or hotfix build UI
on:
  push:
    branches: ["feature/*", "hotfix/*", "develop", "master"]

jobs:
  build-and-push-image:
    if: "!contains(github.event.head_commit.message, '[release]')"
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: engineering-research-and-development/dsp-true-connector-ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build TC DSP UI app
        run: npm run build --configuration=production

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          no-cache: true
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:test
          labels: ${{ steps.meta.outputs.labels }}
